exclude:
  - node_modules
  - server/node_modules
  - vendor
  - .bundle
  - package-lock.json
  - package.json
  - .gitignore
  - .gitmodules

title: "Сайт доставки"
description: "Сервис быстрой доставки"
baseurl: ""
url: ""

markdown: kramdown
theme: jekyll-theme-primer

plugins:
  - jekyll-feed